# Generated by Django 5.1.1 on 2024-10-05 22:07

import django.core.validators
import formulario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10, unique=True, validators=[formulario.validators.validar_rut])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Correo electrónico inválido.')])),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=15)),
                ('mensaje', models.TextField()),
                ('reg_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contactos',
            },
        ),
    ]
